### PR TITLE
Remove debug logging from docker apache config

### PR DESCRIPTION
**Pull request by jechols**
Seems like most of the logging this does is meaningless.  The Django logging is far more useful (seeing raw SQL, for instance).  Can we just get rid of the debug Apache logging?

### CODE REVIEW

**Comment by AndrewGearhart** [comment]
I'm onboard with this. Would prefer if there was a single place where this could be changed in, for example, the .env file though.

**Comment by jechols** [comment]
@AndrewGearhart Now with infinite configurability!

**Comment by jechols** [comment]
@jduss4 @techgique @lsat12357: Thoughts?  This isn't urgent, and doesn't affect UO's production, so I'm not going to push anybody to merge.  But I'm curious if anybody knows why we set this to debug in the first place....

**Comment by jduss4** [comment]
The collective memory at UNL apparently does not remember!

**Comment by techgique** [comment]
I like the configurability though :)

**Pull request merged**
