### PR TITLE
Improve Python dependency handling

### LINKED ISSUE #444: Don't overwrite `requirements.lock` on docker setup
By default we should *read* the lockfile, not pull in the latest and greatest and overwrite it.  All our dev environments end up different the way we're currently doing things!

### LINKED ISSUE #568: Install python dependencies *always*
When the docker environment starts up, we only run the pip update operation if `ENV/lib` doesn't exist: https://github.com/open-oni/open-oni/blob/dev/docker/_startup_lib.sh#L13-L16

This is not a good idea.  It probably saves us a few seconds on startup, but it causes us to have to blow away `ENV` every time something in our requirements changes, which slows things down a great deal in those cases.  It also wastes time trying to debug why a given library claims not to be present when we know we just added it to the requirements.

I believe it is likely we could just blindly run the pip install without any trouble.

### PR DESCRIPTION
**Pull request by techgique**
- Install Python dependencies from `requirements.lock` for reproducible builds
  - Close #444
- Always install dependencies from `requirements.lock` on web container start
  - Close #568 

## Submitter Checklist

- [x] Verify all tests pass
  - Run tests with `docker-compose -f test-compose.yml -p onitest up test`
- [x] Update `README.md` and `docs/` as necessary
  - [x] If a `manage.py` command is added, deleted, or modified its help text must
    be valid and it should be documented in detail in
    `docs/advanced/admin-commands.md`
- Update `CHANGELOG.md`
  - [x] Describe change(s) in appropriate section(s)
  - [x] List self in Contributors section
- If a release PR:
  - [x] In `CHANGELOG.md`, replace `[Unreleased]` with version and update compare link
  - [x] Update `core/version.py` with new version
- [x] Resolve merge conflicts
- [x] @mention individual(s) you would like to review the PR
  - Reviews for releases must come from a reviewer at another institution

## Reviewer Checklist

- [ ] Verify all tests pass
- [ ] Review changes for behavior, bugs, and compliance with [Development
  Standards](https://github.com/open-oni/open-oni/tree/dev/CONTRIBUTING.md#development-standards)
  - Request the submitter make any changes rather than pushing changes yourself.
    Otherwise ask another reviewer to look at any changes you have made.
- [ ] If a release, follow the [Release
  Checklist](https://github.com/open-oni/open-oni/tree/dev/CONTRIBUTING.md#release-checklist)

### CODE REVIEW

**Comment by techgique** [comment]
I don't see anything in docs etc we need to change for this. I think we'll need to change things for a separate updating process, for which I'm imagining we'll just add a separate `pip-update.sh` script.

Question on this change… do we want to pin versions on `pip`, `setuptools`, and `virtualenv` that are updated before creating the virtualenv as well? :dizzy_face:

**Comment by jechols** [comment]
Oh, looks like the docs for CentOS already specified to install from the lockfile, huh.

I think this is a good change overall.  I don't know the answer about pip/setuptools/virtualenv.  I think some dependencies are predictable, but even a pip update hosed our install not too long ago.  If we want to ensure absolutely reproducible builds in the Docker image, I think we may have to freeze everything... but even that is no guarantee, given we've had at least one Ubuntu package burn us, too.  I just don't know.

**Comment by techgique** [comment]
With regards to making things as reproducible as possible, I've been researching and testing things. From the reading I did I get the impression that things are moving in the direction of `venv` as opposed to `virtualenv`. There are some technical differences but it looks like things are converging on standardizing use of `venv` as it's shipped standard with Python. Some of the other dependency-handling Python tools seems to be updating their code to prefer it. One important factor (though it probably isn't so relevant to Docker deployment) seems to be that upgrading to newer versions of Python will break with `virtualenv` but won't with `venv`. Here's some of the reading I found:
- https://stackoverflow.com/questions/41573587/what-is-the-difference-between-venv-pyvenv-pyenv-virtualenv-virtualenvwrappe
- https://github.com/pypa/pipenv/issues/15
- https://github.com/pypa/virtualenv/issues/1366

So I propose we switch to `venv`. This requires installing the `python3-venv` package in our Ubuntu-based Dockerfile and changing the `virtualenv` command.

The other aspect of making things more reproducible are these lines in `pip-install.sh`:
```bash
  pip3 install -U pip
  pip install -U setuptools
  pip install -U virtualenv
```

These will install the latest versions of these packages before our virtual environment is created, which causes more variance between ONI Docker deployments. I experimented with installing different packages via Ubuntu in the Dockerfile followed by only creating the venv and installing our requirements file.  No matter how I did it, it resulted in failure to build the wheels for the packages. This happens for multiple packages: mysqlclient, pymarc, pysolr, sgmllib3k, and worldcat.

```
test_1   |   ----------------------------------------
test_1   |   Failed building wheel for mysqlclient
test_1   |   Running setup.py clean for mysqlclient
test_1   |   Running setup.py bdist_wheel for pymarc: started
test_1   |   Running setup.py bdist_wheel for pymarc: finished with status 'error'
test_1   |   Complete output from command /opt/openoni/ENV/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-1ujj_fsj/pymarc/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpudldas3xpip-wheel- --python-tag cp36:
test_1   |   /usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
test_1   |     warnings.warn(msg)
test_1   |   usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
test_1   |      or: -c --help [cmd1 cmd2 ...]
test_1   |      or: -c --help-commands
test_1   |      or: -c cmd --help
test_1   |   
test_1   |   error: invalid command 'bdist_wheel'
```

At first I thought this was a dead end problem. But upon further reading I don't think this is actually a problem for our purposes. Building local wheels from the packages not providing wheels for install on PyPI doesn't provide any benefit. There won't be any future installs of the packages that would be sped up when we're operating in both a virtual environment and isolated containers. So I added the flag for the `pip` command that disables them.

Tests are passing and everything seems to be working properly. I think this is the most reproducible build we can achieve without changing the base Docker image we use, which we have a separate issue for: https://github.com/open-oni/open-oni/issues/434. Please let me know if I'm overlooking anything or you see problems in testing.

**Review by jechols — APPROVED** [review]
This looks good, this is a wonderful improvement, and I ran the stack and ingested ~800 pages locally, so I give it two 👍 

I don't think we want to have all those `docker/*` scripts executable since they should never be run outside the container.  But that's not really worth holding this up any longer.  Just something to ponder for another time.  Merge whenever you're ready.

**Pull request merged**
