### PR TITLE
Use the list of SOLR languages for advance search by language

### PR DESCRIPTION
**Pull request by johnscancella**

### CODE REVIEW

**Comment by johnscancella** [comment]
I happened upon this because I had loaded a Arabic language newspaper. Then if you go to the advance search it fails because `[code for code,key in _distinct_values(models.Title, "languages")]` returns `None`, which then causes `lang_choices.extend((l, models.Language.objects.get(code=l).name) for l in lang_codes)` to fail.

**Comment by johnscancella** [comment]
Perhaps it would be better to limit the query of languages to only titles that have issues?

**Comment by techgique** [comment]
If I'm understanding this correctly and it will populate with options which are going to frequently return 0 results, that doesn't seem wise to me. I know we've come across situations like this in other projects and @karindalziel has always leaned on the side of not including options which return 0 results too. It makes search interfaces frustrating to use. Lots of trial and error which we should be able to avoid with our programming on the back end.

This is kind of tangential, but I'm curious. In the case of the code returning `None`, is that because of missing language information in the metadata, or is something especially tricky with Arabic?

Maybe instead of the proposed code change that removes the use of a Title's languages, we only revert to the entire list of Solr languages if `None` is returned from the Title's languages?

**Comment by techgique** [comment]
John, you may have answered my tangential question. It's returning `None` because the title doesn't have issues?

**Comment by johnscancella** [comment]
@techgique if you do a `title_pull` and then `load_titles` you get something like 25k titles. The way the code currently is, it will grab all the languages from those 25k+ titles, so you already have many that will return 0 results if you haven't loaded many batches. If you want to ensure results only on languages that are loaded I would limit the search to be only on titles that have issues.

**Comment by techgique** [comment]
Ah okay. That sounds like a good way forward here then

**Comment by johnscancella** [comment]
@techgique I updated the code to only pull languages from titles that have issues.

**Comment by johnscancella** [comment]
If anything I would imagine it would be a improvement since we are limiting the results in the database.

**Comment by techgique** [comment]
It looks good to me, but @jduss4 is much more familiar with the advanced search and I defer to her in terms of how it works with our site.

@johnscancella Limiting results further can potentially still be a slower query for the database. If anyone's database is really huge and the updated query does turn out to be a little slower, an additional index on the Language model's `name` field might help, as the query is ordering by that field: https://github.com/open-oni/open-oni/blob/master/core/models.py#L1150

**Comment by jechols** [comment]
Thanks, @johnscancella!

**Pull request merged**
