### PR TITLE
Feature/adv search

### PR DESCRIPTION
**Pull request by jduss4**
Sets up UI closer to @karindalziel 's specs
Adds more fields to be available via searching
Still a lot to do, but this is a pretty good first crack at it

### CODE REVIEW

**Comment by karindalziel** [comment]
It seems like not all the options are making it into the search results screen. For instance: 

screen shot 2016-07-29 at 9 32 41 am

gives you 

screen shot 2016-07-29 at 9 32 34 am

So you can't remove the county or the state.

**Comment by karindalziel** [comment]
Language and Frequency drop downs do not match that's int he batches, which I think would be confusing for users:

screen shot 2016-07-29 at 9 42 47 am

screen shot 2016-07-29 at 9 42 54 am

**Comment by karindalziel** [comment]
OK, all done reviewing the front end, looks great! I think the issues mentioned above could be handled in a future PR if we want to get this one in.

**Comment by jduss4** [comment]
This PR wasn't meant to touch the advanced search results.  Once we add filters to the results, then things like county will show up as dropdowns and none of the string concat stuff will show up at the top....that's my plan.  But I can add county in if we need it!

**Comment by jduss4** [comment]
I have restricted frequency to only relevant entries, but I am not sure it will be as easy with the languages.  For now, I would recommend simply changing your language settings (SOLR_LANGUAGES) to reflect the ones you would like as options.

**Comment by karindalziel** [comment]
Everything looks good to me 👍🏽

**Pull request merged**
