### PR TITLE
updated About API page to the best of my ability

### PR DESCRIPTION
**Pull request by srabun**
@karindalziel @kestlund Please review text - I updated the language as much as possible to remove references to Chronicling America and NDNP, however, I'm not certain that our Open-ONI API works in the exact same way, so I definitely need one of you to look over the changes. I have a feeling more updates will be needed later as well...THanks!

### CODE REVIEW

**Comment by jduss4** [comment]
We had started labelling things Open ONI elsewhere, so we might want to consider dropping the hyphens from the name of the organization.  Or we need to do some renaming elsewhere!

Otherwise, my only thoughts are that the API still currently functions the same way, so we can tell users about tools like adding format=json to the URL.
:)

**Comment by srabun** [comment]
Good call Jessica, we do need to normalize Open ONI/Open-ONI one way or the other...I hadn't thought of that...

**Comment by jechols** [comment]
Posted this on our doc, but it's good to have here, too:

I think we decided against the dash for the official name, since it doesn't really make a lot of sense when you expand the acronym: "Open-Online Newspaper Initiative". The repo has the dash because that's how github spaces things. The code tends to be just "openoni" because dashes aren't allowed as identifiers in code.

**Comment by srabun** [comment]
Ok, I will fix both pages to read Open ONI

**Comment by srabun** [comment]
@karindalziel @jduss4 Ok, I just went in and replaced Open-ONI with Open ONI (no dash) - I think it worked? just need to have someone review merge pull request?

**Comment by jechols** [comment]
This has some merge conflicts... I'll try to look at it when I have some time, but it may be a while if it isn't an easy resolution

**Comment by jduss4** [comment]
I can probably take a look later today or tomorrow

**Comment by jduss4** [comment]
@edsu will anything need to be updated for the "about api" page after your IIIF additions?

**Comment by edsu** [comment]
Yes, I can I was planning on updating the docs to reflect the new IIIF functionality. I will do it on my iiif branch though. Does that work? Or is there a better way to go about doing it?

**Comment by jduss4** [comment]
That sounds good.  I'll figure out the conflict tomorrow morning and get it merged in!  :)

**Comment by jduss4** [comment]
I rebased locally, then merged with master in the neighborhood of this commit:
https://github.com/open-oni/open-oni/commit/84c06020e2f72845d26b06611f401ba0d4df5fd6

**Pull request closed without merging**
