### PR TITLE
Use Bootstrap classes on skip link

### LINKED ISSUE #480: a11y Skip Link Bootstrap Tweak
https://getbootstrap.com/docs/3.4/getting-started/#skip-navigation

The `tabfocus="-1"` part no longer seems necessary due to Chrome having fixed it long ago and versions of IE which required it no longer being supported. But the `sr-only` and `sr-only-focusable` classes would be preferable to the manual `skiplink` class I previously implemented.

Another small fix I found in notes of mine I missed before.

### PR DESCRIPTION
**Pull request by techgique**
Rather than simple custom class

Closes #480

### CODE REVIEW

**Comment by jechols** [comment]
Though I appreciate the intent here, it's a lot easier to do specific custom styling when the class is ours rather than bootstrap's.  To explain, UO has a custom approach for the skip link - see https://oregonnews.uoregon.edu/ and hit tab once.  Now with just the bootstrap styling, there are no safe CSS rules we could use to match this.  If we add a rule for `sr-only-focusable`, it applies to anything using that bootstrap class, which is definitely not what we want since that specific skip link is using a custom CSS transition.

I'd argue that unless there's a need for this kind of thing, we should just leave it alone.  If anybody is doing styling in their theme based on the current class, this means they have to change their theme to potentially override the entire ONI `body_content` block just to get the behavior they want again.

**Comment by techgique** [comment]
Ah okay. Could we leave that `skiplink` class in addition to the Bootstrap ones for theme-specific customization? Will that be enough to allow you to override / tweak the Bootstrap behavior to your liking?

I should have noted that as a migration concern because of possible theme customization too.

**Comment by jechols** [comment]
I'll take a look locally and see if it's solvable, but I still don't think this is the right approach.

First, I think breaking backward compatibility right now should be done only where it's absolutely necessary since we have a deadline.  We take a QA hit or a potential delay if we're re-testing stuff that was already known to work.  This change, even if it were 100% unarguably correct, doesn't actually improve the application in any way, and isn't relevant to a 1.0 release.

Second, we're requiring adopters to "undo" the bootstrap styling if they want their skip link to function as a special widget.  This means anybody doing their own skip link (granted that's probably just UO for now) has a migration effort.

Third, a skip link is not simply invisible-until-focused text.  Many sites have a particular way they want their skip link(s) to display.  Generic CSS rules should only be applied to truly generic widgets, which I'd argue skip links are not.

Bootstrap's approach is to just mix and match their rules to get what you need.  That works fine when you're building an internal site, but when branding an open source project, it's nice to apply styling primarily via CSS rules, as opposed to rewriting the entire template.

**Comment by jechols** [comment]
The UO theming can be applied if we put "skiplink" back in the list of classes.  This might mitigate the migration notes - at least in our case it seems to.  However, with the default theme, the entire page "jumps" when you tab to the skip link.  This is a change from how it behaves on the dev branch.

And I still feel we should let this one go.  We have very simple styling right now that works well enough for a default setup, and makes it trivial to customize it as needed.  If a site wants to do something like show the skip link, it would be a massive pain to undo all the sr-only styling, for instance.  We don't need to force them to do it "our" way.

That said, if the core maintainers (other than myself) want this, I think I've said my piece and we can move on.

**Comment by techgique** [comment]
We discussed this in more detail on Slack, but I failed to explain a major reason for wanting to go this approach is to rely on Bootstrap's more cross-browser compatible CSS rather than my own.

Will retain the `skiplink` class for non-default theme overriding, and broader review of Bootstrap-centric markup in our default theme will be revisited in the future.

**Pull request merged**
