### PR TITLE
Fix/utf8

### PR DESCRIPTION
**Pull request by jechols**
This allows emojis into databases where they would otherwise not work. This isn't useful for the vast majority of users (not much emoji use in historic papers 😁 ), but very important if you're pulling born-digital PDFs in, where emoji use is on the rise. At least, it is for us.

## Submitter Checklist

- [x] Verify all tests pass
  - Run tests with `docker-compose -f test-compose.yml -p onitest up test`
- [x] Update `README.md` and `docs/` as necessary
  - [x] If a `manage.py` command is added, deleted, or modified its help text must
    be valid and it should be documented in detail in
    `docs/advanced/admin-commands.md`
- Copy the changelog file template in `changelogs/` to a new file in the
  same directory named following the `YYYY-MM-DD-branch_name.md` pattern with
  the day's date and your branch name
  - [x] Describe change(s) in appropriate section(s)
  - [x] List self in Contributors section

## Reviewer Checklist

- [ ] Verify all tests pass
- [ ] Review changes for behavior, bugs, and compliance with [Development
  Standards](https://github.com/open-oni/open-oni/tree/dev/CONTRIBUTING.md#development-standards)
  - Request the submitter make any changes rather than pushing changes yourself.
    Otherwise ask another reviewer to look at any changes you have made.
- [ ] If a release, follow the [Release
  Checklist](https://github.com/open-oni/open-oni/tree/dev/CONTRIBUTING.md#release-checklist)

### CODE REVIEW

**Comment by jechols** [comment]
We were unable to get this to work as-is for our setup (Historic Oregon Newspapers), so I'm not sure it makes sense to merge. We actually had trouble running the migration: it caused the database to essentially fail due to separate issues with indexing.

I think I have to close this, and we'll need to rethink the problem. Most people won't run into emojis in their newspapers, but if they do, we need a solution that is truly general-case and bulletproof.

**Comment by jechols** [comment]
Maybe what we really need is a migration script, not a simple set of SQL commands. Something that can determine MySQL / MariaDB version and do the appropriate tasks needed for proper UTF8 support....

**Comment by jechols** [comment]
It appears I was planning to look closer at this, get it running in production (we have it on staging, just not prod), and then see if there was any easy way to unit-test the thing.

And then I lost track of this entirely. So... I'll deploy to UO's production and if all goes well I'll move this PR out of draft.

**Review by techgique — APPROVED** [review]
Tested locally with already ingested batches. Migrated successfully.

Added emoji to a batch and it loaded successfully here but crashed loading while on another branch.

Running tests succeeds.

Looks good!

**Pull request merged**
