### PR TITLE
Remove scripts/ directory with PyMarc test script

### LINKED ISSUE #470: Review scripts/ directory
Do we still need this? I think what's in there should be moved to the separate ONI scripts repository. I think this should only be for essential non-Docker scripts if we're going to keep it.

### PR DESCRIPTION
**Pull request by techgique**
Closes #470

### CODE REVIEW

**Comment by techgique** [comment]
@AndrewGearhart This script wasn't used in any of your work with making a local MARC file was it?

**Comment by AndrewGearhart** [comment]
@techgique 
I'm not currently using that (didn't find it when I was building my batch management script)... looks like it would be useful as an alternative to the bash function that I'm currently using. Does it work?

**Comment by techgique** [comment]
@AndrewGearhart I'm not sure. I didn't test it. It wasn't clear to me that it served any useful purpose to us. I just saw that it seems to be testing PyMarc and though I'd ask if it appears of any use to you.

**Comment by techgique** [comment]
My impression from reading it is that it just outputs random country codes from marc files. You may want to adapt it for your use, but as is I don't see it being useful keeping it in the repository.

If you want to circle back around to it, you can get to it using this link to the file in git history: https://github.com/open-oni/open-oni/blob/v0.13.0/scripts/extract_marc_values.py

**Pull request merged**
