### PR TITLE
removes tiny and medium image template tags and methods

### PR DESCRIPTION
**Pull request by jduss4**
these were not called anywhere in the codebase
recommended to use image_url(page, size) instead

closes https://github.com/open-oni/open-oni/issues/372

## Submitter Checklist

- [x] Verify all tests pass
  - Run tests with `docker-compose -f test-compose.yml -p onitest up test`
- [x] Update `README.md` and `docs/` as necessary
- Update `CHANGELOG.md`
  - [x] Describe change(s) in appropriate section(s)
  - [x] List self in Contributors section
- [x] Resolve merge conflicts
- [x] @mention individual(s) you would like to review the PR
  - Reviews for releases must come from a reviewer at another institution

## Reviewer Checklist

- [x] Verify all tests pass
- [x] Review changes for behavior, bugs, and compliance with [Development
  Standards](https://github.com/open-oni/open-oni/tree/dev/CONTRIBUTING.md#development-standards)
  - Request the submitter make any changes rather than pushing changes yourself.
    Otherwise ask another reviewer to look at any changes you have made.
- [x] If a release, follow the [Release
  Checklist](https://github.com/open-oni/open-oni/tree/dev/CONTRIBUTING.md#release-checklist)

### CODE REVIEW

**Comment by techgique** [comment]
Is it possible to deprecate `custom_size_image_url` and just name it more generally like `iiif_image_url`? Perhaps [the Django deprecation approach](https://docs.djangoproject.com/en/2.2/internals/contributing/writing-code/submitting-patches/#deprecating-a-feature) can be used here by us so we can avoid breaking things _and_ move towards a friendlier tag name?

**Comment by jduss4** [comment]
How would you feel about just `image_url` ? I don't think that we need to include anything IIIF specific at this point, that all happens behind the scenes.

**Comment by jduss4** [comment]
Hmm after looking at that deprecation link, that looks like that's how django itself deprecates methods, but we may want to look into something like this library:  https://pypi.org/project/Deprecated/
I'll poke around a bit!

**Comment by techgique** [comment]
I'm wondering if the tiny and medium functions ought to be deprecated as well rather than just removed. Even if we don't see them used anywhere, it's probably good practice for us to deprecate them first and remove them in a later release. Thoughts?

**Comment by jduss4** [comment]
I have been unable to determine if the deprecation library is working as expected, because I am not seeing any warnings locally when I change thumbnails to "medium" images in the code, nor when I write a test for a deprecated method (such a test not reflected in the above code).

I am curious if anybody else can see deprecation warnings in a development setup.

**Review by jechols — APPROVED** [review]
This looks good to me!

I think I mentioned it already, but in the future please avoid changing files that aren't part of the core feature.  There isn't really any need to separate the fixture files and reformat the `fixtures = ...` lines, and doing so can cause unnecessary merge conflicts.  Personally I'd prefer more focused fixture JSON rather than lots of files that are implicitly interdependent (try using just `page.json` in a simple test).

**Review by jechols — DISMISSED** [review]
Oops - I didn't do a good review here.  I forgot the checklist 🤦‍♂️ 

You need to update the changelog since stuff is being deprecated.

**Comment by jduss4** [comment]
@jechols your complaint has been formally noted, but I'm sticking with the change because we already hashed it out in the slack channel several months ago :)  I will make the alterations to the changelog, however!  Thanks!

**Comment by jduss4** [comment]
Okay, while making the changelog, I think this PR is not complete.  After initial review, I had added the deprecation library and some warnings but wasn't able to see any of them in logs anywhere with docker.  Sounds like @techgique wasn't either.  I think that I would like to remove them AND the methods they were deprecating, since those methods were not used anywhere in our code and I find it unlikely they are used by themes in our current ecosystem (I think at the time I checked UNL, Penn, and UO's code).

Thoughts?

**Comment by techgique** [comment]
I'm okay with that. If we remove a method that *is* used elsewhere, I'll be a bit more hard-nosed about figuring out deprecation messages :)

**Pull request merged**
