### PR TITLE
Remove Topics

### PR DESCRIPTION
**Pull request by jduss4**
Removes topics from templates, views, models
Also removes the topic loading scripts

### CODE REVIEW

**Comment by jechols** [comment]
I'm going to look more into migrations and see if I can figure out why this is only working on a clean DB.

**Comment by jechols** [comment]
Migrations aren't running.  At all.  We're going to have to figure this out, but for now I'm closing this.  Maybe I can fix it this sprint, but we need to figure out migrations for sure.

**Comment by jechols** [comment]
FYI branch might be fine - just closing the PR until we know how to make migrations work again.

**Comment by jduss4** [comment]
I think the branch is probably mostly fine except for the actual migration file.

**Pull request closed without merging**
