### PR TITLE
Adds city dropdown to navbar for searching

### PR DESCRIPTION
**Pull request by jduss4**
Puts into context_processors to make accessible everywhere

### CODE REVIEW

**Comment by jduss4** [comment]
This feature was mostly to help out Nebraska's theme, so if people feel strongly that it shouldn't be in here, let me know and I'll try to figure out a way of not having it in core at all.....but it would make my life a lot easier if it can stay!  :)

**Comment by techgique** [comment]
@karindalziel You may want to check out the style of the select causing the search form to drop to a second row in the menu depending on which browser one uses? For me, Firefox looks different than Chrome and does that. No idea if the difference is there in Mac and/or Windows browsers too.

**Comment by karindalziel** [comment]
capture
untitled-1

**Comment by karindalziel** [comment]
Created issue for the navigation spacing problem: https://github.com/open-oni/open-oni/issues/235

**Pull request merged**
